### ISSUE TITLE
Missing interfaces of Skia

### ISSUE THREAD

**Issue by danger89** [aseprite/skia#10]
You removed (or at least missing) quite some interfaces in your build:

- GrDirectContext
- core/SkAutoMalloc.h
- dawn/webgpu_cpp.h
- dawn_native/DawnNative.h
- dawn/dawn_wsi.h
- dawn/dawn_proc.h
- ..
- ...

I would like to use your Skia static library to build the Skia Hello World example.

Regards,
Melroy

**Comment by dacap** [comment]
Hi @danger89, we haven't removed any file from the original Skia branch ([chrome/m81](https://github.com/aseprite/skia/tree/chrome/m81)). You might be looking for the master branch of Skia, but we didn't update laf and Aseprite to it yet (or to the latest chrome/mXX branch).
