### ISSUE TITLE
Can't build skia (macOS)

### ISSUE THREAD

**Issue by KethQv** [aseprite/skia#12]
I didn't have any issues with all the steps before this one, but when I ran the following line: 

`ninja -C out/Release-x64 skia modules`

This error showed up:

    ninja: Entering directory `out/Release-x64'
    ninja: error: '../../third_party/externals/icu/scripts/make_data_assembly.py', needed 
    by 'gen/third_party/icu/icudtl_dat.S', missing and no known rule to make it

Is there something I'm missing? I'm stuck, please help :[

**Comment by dacap** [comment]
Hi there @KethQv, I'm not sure but maybe the `python tools/git-sync-deps` step failed? give a try to run it again.

**Comment by KethQv** [comment]
It worked thanks:) 👍
